services:
  - name: quinta-ypua-api
    type: web
    runtime: dotnet
    plan: free
    region: frankfurt        
    branch: main              
    rootDir: API              

    buildCommand: >
      dotnet restore &&
      dotnet publish -c Release -o out

    startCommand: >
      dotnet out/API.dll

    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}

      - key: ASPNETCORE_ENVIRONMENT
        value: Production
